Repository Celebr8/frontend, pull requests merged in 2019-08, with the labels that each got.

#308 Add review rating Search Page #293
  src/components/ListingCard/ListingCard.css
  src/components/ListingCard/ListingCard.js
Labels: enhancement, frontend

#317 Fix typo in first steps header #315
  src/translations/en.json
Labels: Trivial

#327 En.json changed whichost to celebr8
  README.md
  app.json
  src/components/EditListingCapacityPanel/EditListingCapacityPanel.js
  src/forms/EditListingCapacityForm/EditListingCapacityForm.js
  src/marketplace-custom-config.js.orig
  src/translations/en.json
Labels: enhancement, frontend

#344 Resolve conflict material ui #343
  app.json
  package.json
  src/forms/EditListingCapacityForm/EditListingCapacityForm.js
Labels: bug, frontend

#331 FirstStepsTabs.js update whichost to celebr8
  src/components/FirstStepsTabs/FirstStepsTabs.js
Labels: enhancement, frontend

#345 Revert "Footer.js update whichost to celebr8"
  src/components/Footer/Footer.js
Labels: bug

#347 Resolve parsing error in footer #346
  src/components/Footer/Footer.js
Labels: bug

#350 Fix parsing error in Legal Deals #349
  src/components/LegalsDeals/LegalsDeals.js
Labels: bug

#354 Re-branding About Us Page #353
  src/translations/en.json
Labels: enhancement

#356 Replace 'Whichost' above 'Experience the Magic' #355
  src/translations/en.json
Labels: enhancement

#358 Re-branding section deals Landing Page #357
  src/components/SectionDeals/SectionDeals.js
Labels: enhancement

#360 Re-branding FirstStepsTabs #359
  src/components/FirstStepsTabs/FirstStepsTabs.js
Labels: enhancement

#362 Rebrand email addresses on platform #361
  src/components/TermsOfService/TermsOfService.js
  src/containers/HelpCenter/FAQPage/FAQPage.js
  src/containers/Legals/CommunityGuidelinesPage/CommunityGuidelinesPage.js
Labels: enhancement

#364 Add mailto for support@celebr8.co #363
  src/containers/Legals/CommunityGuidelinesPage/CommunityGuidelinesPage.js
Labels: enhancement
